### ISSUE TITLE
Cant run example code "rotary_encoder"

### ISSUE THREAD

**Issue by DieSteinhose** [PedalPi/Physical#9]
Hello, i have already reinstall Raspbian Stretch lite on my Raspberry Pi 3B and Zero W. When i try to run the example code

"from gpiozero import RotaryEncoder

def change(value):
    if value > 0:
        print("clockwise")

    else:
        print("counterclockwise")

rotary = RotaryEncoder(4, 17)        
rotary.when_rotated = change"

then it reply

"sudo python3 rot_test.py
Traceback (most recent call last):
  File "rot_test.py", line 1, in <module>
    from gpiozero import RotaryEncoder
ImportError: cannot import name 'RotaryEncoder'"

I have already tried with python 2 and 3, with and without sudo. If i try to install via pip (not pip3) it can’t install, like my last issue here.

**Comment by SrMouraSilva** [comment]
Hello @Logimann. First, is a bad practice execute all with `sudo`. If an unintended user or program has access to the running program, it can do unwanted things!

Ok, now about the error:

> from gpiozero import RotaryEncoder
> ImportError: cannot import name 'RotaryEncoder'"

A correct example is:

```python3
from physical.rotary_encoder import RotaryEncoder
def change(value):
    if value > 0:
        print("clockwise")
    else:
        print("counterclockwise")

rotary = RotaryEncoder(4, 17)
rotary.when_rotated = change
```

Could you tell me where you were informed that the code should be imported in this way?

In the future, however, this component is likely to be integrated into gpio-zero, but there are no plans for the team to offer this support. https://github.com/RPi-Distro/python-gpiozero/pull/482

**Comment by DieSteinhose** [comment]
Thanks for the fast answer.
The code is from " Raspberry-Physical/physical/rotary_encoder.py" beginning with line 24.

Unfortunately the code didn't run. After is sende the command "python3 led/rot_test.py", i have not receive any feedback.

**Comment by SrMouraSilva** [comment]
@Logimann 

> Unfortunately the code didn't run.

Do you are correctly connected the pins (BCM 4 and 17)?
https://pinout.xyz/pinout/pin7_gpio4

>  After is sende the command "python3 led/rot_test.py", i have not receive any feedback.
Observe the code. Only will print clocksomething if the rotary encoder are "rotated".
But, the code will finish because there are nothing to say "hey, wait!".

Adapting [a gpio zero example](https://gpiozero.readthedocs.io/en/stable/), I added the method `pause()`

```python3
from physical.rotary_encoder import RotaryEncoder
def change(value):
    if value > 0:
        print("clockwise")
    else:
        print("counterclockwise")

rotary = RotaryEncoder(4, 17)
rotary.when_rotated = change

from signal import pause
pause()
```

Please, test.

**Comment by DieSteinhose** [comment]
It works now, thanks!

Is there any possibility to run this code with sudo? I try to combine this with ws2812 led's and this code required root.

**Comment by SrMouraSilva** [comment]
@Logimann, if the gpiozero works with sudo, Physical will works too

Hey, please share your project here! A video or the source code will be awesome!

**Comment by DieSteinhose** [comment]
If i try to run with sudo i got this:

pi@raspberrypi:~ $ sudo python3 led/rot_test.py
Traceback (most recent call last):
  File "led/rot_test.py", line 3, in <module>
    from physical.rotary_encoder import RotaryEncoder
ImportError: No module named 'physical'


When I'm done with the project, I like to share it. This should be around the end of next week.

---edit
gpiozero works fine with sudo

**Comment by SrMouraSilva** [comment]
Did you try to understand the error that appeared?

Try install with sudo...
